insert into users(userId,userName) values(559478,'Dominic'),(559477,'Gavin')
insert into chores(chore_title,chore_description,chore_payout) values
('Take Out Garbage','Remove garbage bag and make sure a tied bag is deposited in the outside garbage can then a new bag is put in the empty inside garbage can. This can be done as often as it is needed.',.1),
('Unload Dishwasher','Empty a clean dishwasher and put away all the dishes including the silverware and all cabinets are closed when complete. This can be done as often as it is needed.',.1),
('Run Washer with Supervision','Load the proper amount of clothes and detergent in the washer and turn on. Easiest time to do this is after the laundry is brought down. Can be done as long as the washer would be a reasonable load. ',.1),
('Return Empty Garbage cans(per can)','When the garbage people empty the garbage cans you put them neatly back where they go with the lids on them. This gets paid per can that is correctly put back. This only happens once a week. ',.1),
('Load Dryer(move from washer to dryer)','Move clean laundry from the washer to the dryer. Clean the dryer lint off and put it in the garbage, add a dryer sheet and turn on for the appropriate amount of time. This can be done as long as there is something to put in the dryer. ',.1),
('Unload Dryer(carry up)','Empty Dryer and close dryer door. Bring upstairs. If there isnt anything in the dryer you cant bring it up. ',.1),
('Shower','On your own you determine that you’d like to get a shower. The best times to do this are either first thing in the morning or right after dinner. If you want to shower in the evening you MUST let mom or dad know BEFORE dinner. You can get a shower everyday if you want but you will only get paid for up to 4 times. ',.1),
('Sweep Steps','Steps will be cleaned of all larger garbage and then will be swept starting at the top and working your way down one step at a time. When you get to the bottom all garbage that was on the steps should be swept up and thrown away. Nothing should be on the steps when you are done. This can only be done once a week. ',.25),
('Sweep Floors(per room)','The floors will be clear of any dirt and will not have stuff all over them. No blankets,clothes or toys will be left out. All garbage will be swept up and thrown away. The rooms that can be swept are the Kitchen, Living Room, Bathroom and Your room. All rooms are swept with a broom. Rooms can only be swept once per week. ',.25),
('Clean Bathroom Sink','Sink will be cleaned up, all the stuff that doesnt belong on the sink will be put away and the sink will be cleaned. There should be no hair or toothpaste on the sink when you are done. This can only be done once a week',.25),
('Load Dishwasher','This is actually loading the dishwasher meaning that the machine should be ready to be washed and that there are actually no dishes that were missed around the house. All silverware and cups should be cleaned up around the house and deposited in the dishwasher. The best time to do this chore is right after dinner, the dishes are freshest and arent too bad to clean off. Can only be done if there are dishes to do it. ',.25),
('Carry Clothes Downstairs','Clothes will be cleaned up and brought downstairs in either a bag or basket form. When they get downstairs they will not be left sitting at the bottom of the steps. Should be completed as soon as the basket in the bathroom gets or is almost full. ',.25),
('Fold and put away Laundry','Laundry will be either folded or hung appropriately. When folding is completed the hung clothes will be put in the appropriate closet and then your clothes will be put away in your dresser. Your brothers’ clothes will be set on top of their dresser and mom and dads clothes will be left in the basket and set on our bed. When you are done folding laundry all the hangers should be put away and the dryer sheets should be thrown away. The best time to do this is right after you bring the laundry upstairs. ',.25),
('Clean Shower','When you clean the shower the shower will have all the soap and louffa’s put where they go and the floor and walls need to be cleaned. If there are washcloths in the shower then need to be put into the laundry. This can be done only once per week. ',.5),
('Take Garbage can to curb(per can)','The garbage needs to go to the curb on Thursday night. Each can that has at least a bag of Garbage in it needs to be taken to the curb. Use the wheels and if you need to roll it through the grass and bring it back over to where we put the garbage.',.5),
('Practice Instrument','Self explanatory I think. Practice should be about 25 minutes. It should break down to about 5 minutes to setup and breakdown your instrument and I expect to hear twenty minutes of practice. The music you practice should either be something that is challenging to you or something new that you are learning. Once again you can practice every day if you want to but will only be paid for 4 times a week.',.5),
('Clean Toilet','The toilet needs to have both lids and the bowl cleaned out. Cleaner should be put in the bowl first then you clean the seats. When the toilet is all done the carpet should be straightened out and the lids should be closed. This can only be done once a week. ',.75),
('Chores','Chores(litter or food and water) needs to be done seven days a week if possible. If you need to redo your chore for the day you will lose $.50 per time. Every day the Litter should be swept off the floor and the box should be scooped all the way to the bottom. Food and water should be filled everyday. The water bowl should be cleaned at least once per week. ',2.00)


